change npx hint --telemetry=off .
 change npx hint --telemetry=off . to npx hint  . 
because in my local it gives me no error but in GitHub gives Invalid option '--telemetry' - perhaps you meant '--help'?
Error: Process completed with exit code 1.